### PR TITLE
Revert "Set marker after signature calculation for hotels."

### PR DESCRIPTION
**Pull request by semenyukdmitry**
It actually breaks things.

### CODE REVIEW

**Comment by dyatlov** [comment]
lol, guys..

**Comment by dyatlov** [comment]
@sadfuzzy can you comment on this pls?
@semenyukdmitriy what exactly it breaks?

**Comment by semenyukdmitry** [comment]
@dyatlov it breaks flights search method.

**Comment by dyatlov** [comment]
reverted

2016-11-07 18:06 GMT+02:00 Semenyk Dmitry notifications@github.com:

**Pull request merged**
